language: node_js
node_js:
  - 12
install:
  - npm ci
jobs:
  include:
    - stage: Staging
      script: CI=false npm run build:staging
      deploy:
        provider: pages
        target_branch: deploy-uat
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        keep_history: true
        on:
          branch: react-branch
